encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.page, name="page"),
    path("search/", views.search, name="search"),
    path("new/", views.new, name="new"),
    path("wiki/edit/<str:title>", views.edit, name="edit"),
    path("random/", views.random_article, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from . import util
from  markdown2 import markdown
from django.urls import reverse
from django.http import HttpResponseRedirect
import random

def helper(request, list_entries):    
    return render(request, "encyclopedia/index.html", {
            "entries": list_entries
        })

def index(request):
    return helper(request, util.list_entries())

def page(request, title):
    article_md = util.get_entry(title)
    if article_md == None:
        return render(request, "encyclopedia/not_found.html", {
            "title": title
        })
    
    return render(request, "encyclopedia/page.html", {
        "article": markdown(article_md),
        "title": title
    })

def search(request):
    if request.method == "POST":
        article_name = request.POST['q']
        articles = []
        
        for entry in util.list_entries():
            if article_name == entry:
                return HttpResponseRedirect(reverse("articles:page", args=(article_name, )))
            elif article_name in entry:
                articles.append(entry)

        if len(articles) == 0:
            return HttpResponseRedirect(reverse("articles:page", args=(article_name, )))
        return helper(request, articles)

class NewArticleForm(forms.Form):
    title_article = forms.CharField(label="Title", widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 800px;'})) 
    content = forms.CharField(label="Description", widget=forms.Textarea(attrs={'class': 'form-control', 'style': 'width: 800px; height: 800px;'}))

class EditContentForm(forms.Form):
    content = forms.CharField(label="Description", widget=forms.Textarea(attrs={'class': 'form-control', 'style': 'width: 800px; height: 800px;'}))

def new(request):
    if request.method == "POST":
        form = NewArticleForm(request.POST)
        if form.is_valid():
            article_title = form.cleaned_data["title_article"]
            article_content = form.cleaned_data["content"]
            util.save_entry(article_title, article_content)

            return HttpResponseRedirect(reverse("articles:index"))
        else:
            return render(request, "encyclopedia/new.html", {
                "form": form
            })

    return render(request, "encyclopedia/new.html", {
        "form": NewArticleForm()
    })

def edit(request, title):
    if request.method == "GET":
        article_md = util.get_entry(title)
        form = EditContentForm({
            "content": article_md
        })

        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "form": form
        })
    else:
        form = EditContentForm(request.POST)
        if form.is_valid():
            article_content = form.cleaned_data["content"]
            util.save_entry(title, article_content)
            return HttpResponseRedirect(reverse("articles:page", args=(title, )))
        
def random_article(request):
    items = util.list_entries()
    random_item = random.choice(items)
    return HttpResponseRedirect(reverse("articles:page", args=(random_item, )))

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit the article "{{title}}"
{% endblock %}

{% block body %}
   <h1> Edit page</h1>
   <h1> {{title}}</h1>
    <form action="{% url 'articles:edit' title %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}<br>
        <button type="submit">Save</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'articles:search' %}" method="post">
                    <input class="search" type="text" name="q" placeholder="Search Wiki">
                    {% csrf_token %}
                    <!--<button type="submit" class="search-button">Search</button>-->
                </form>
                <div>
                    <a href="{% url 'articles:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'articles:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'articles:random' %}">Randome page</a>
                </div>  
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1> Create new page</h1>
    <form action="{% url 'articles:new' %}" method="post">
        {% csrf_token %}
        {{ form }}<br>
        <button type="submit">Create New Page</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Article not found
{% endblock %}

{% block body %}
    <h2>Article "{{ title }}" not found</h2>
{% endblock %}

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }} (Wiki)
{% endblock %}

{% block body %}
    {{ message }}
    {{ text|safe }}
    <h1>{{title}}</h1>
    <div>{{ article | safe }}</div> 
    <form action="{% url 'articles:edit' title %}" method="get">
        <button type="submit">Edit text</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h2>Wiki</h2>
    <form action="{% url 'search' %}" method="post"></form>
{% endblock %}